// Centralized city → [displayName, state, country] map.
// Keys are lowercase for case-insensitive matching.
// Values: [displayName, state, country]
export const CITY_DATA: Record<string, [string, string, string]> = {
  // Rajasthan
  "jaipur": ["Jaipur", "Rajasthan", "India"],
  "kota": ["Kota", "Rajasthan", "India"],
  "jodhpur": ["Jodhpur", "Rajasthan", "India"],
  "udaipur": ["Udaipur", "Rajasthan", "India"],
  "ajmer": ["Ajmer", "Rajasthan", "India"],
  "bikaner": ["Bikaner", "Rajasthan", "India"],
  "alwar": ["Alwar", "Rajasthan", "India"],
  "sikar": ["Sikar", "Rajasthan", "India"],
  "sri ganganagar": ["Sri Ganganagar", "Rajasthan", "India"],
  "bharatpur": ["Bharatpur", "Rajasthan", "India"],
  "pali": ["Pali", "Rajasthan", "India"],
  "pushkar": ["Pushkar", "Rajasthan", "India"],
  "bhilwara": ["Bhilwara", "Rajasthan", "India"],
  "chittorgarh": ["Chittorgarh", "Rajasthan", "India"],
  "dungarpur": ["Dungarpur", "Rajasthan", "India"],
  // Delhi
  "delhi": ["Delhi", "Delhi", "India"],
  "new delhi": ["New Delhi", "Delhi", "India"],
  // Haryana
  "gurugram": ["Gurugram", "Haryana", "India"],
  "gurgaon": ["Gurgaon", "Haryana", "India"],
  "faridabad": ["Faridabad", "Haryana", "India"],
  "hisar": ["Hisar", "Haryana", "India"],
  "rohtak": ["Rohtak", "Haryana", "India"],
  "ambala": ["Ambala", "Haryana", "India"],
  "karnal": ["Karnal", "Haryana", "India"],
  "panipat": ["Panipat", "Haryana", "India"],
  "sonipat": ["Sonipat", "Haryana", "India"],
  "panchkula": ["Panchkula", "Haryana", "India"],
  "rewari": ["Rewari", "Haryana", "India"],
  "yamunanagar": ["Yamunanagar", "Haryana", "India"],
  "bhiwani": ["Bhiwani", "Haryana", "India"],
  "kurukshetra": ["Kurukshetra", "Haryana", "India"],
  // Uttar Pradesh
  "noida": ["Noida", "Uttar Pradesh", "India"],
  "greater noida": ["Greater Noida", "Uttar Pradesh", "India"],
  "lucknow": ["Lucknow", "Uttar Pradesh", "India"],
  "kanpur": ["Kanpur", "Uttar Pradesh", "India"],
  "varanasi": ["Varanasi", "Uttar Pradesh", "India"],
  "agra": ["Agra", "Uttar Pradesh", "India"],
  "meerut": ["Meerut", "Uttar Pradesh", "India"],
  "allahabad": ["Allahabad", "Uttar Pradesh", "India"],
  "prayagraj": ["Prayagraj", "Uttar Pradesh", "India"],
  "ghaziabad": ["Ghaziabad", "Uttar Pradesh", "India"],
  "mathura": ["Mathura", "Uttar Pradesh", "India"],
  "aligarh": ["Aligarh", "Uttar Pradesh", "India"],
  "bareilly": ["Bareilly", "Uttar Pradesh", "India"],
  "moradabad": ["Moradabad", "Uttar Pradesh", "India"],
  "gorakhpur": ["Gorakhpur", "Uttar Pradesh", "India"],
  "firozabad": ["Firozabad", "Uttar Pradesh", "India"],
  "jhansi": ["Jhansi", "Uttar Pradesh", "India"],
  "muzaffarnagar": ["Muzaffarnagar", "Uttar Pradesh", "India"],
  "saharanpur": ["Saharanpur", "Uttar Pradesh", "India"],
  // Maharashtra
  "mumbai": ["Mumbai", "Maharashtra", "India"],
  "pune": ["Pune", "Maharashtra", "India"],
  "nagpur": ["Nagpur", "Maharashtra", "India"],
  "aurangabad": ["Aurangabad", "Maharashtra", "India"],
  "nashik": ["Nashik", "Maharashtra", "India"],
  "thane": ["Thane", "Maharashtra", "India"],
  "navi mumbai": ["Navi Mumbai", "Maharashtra", "India"],
  "solapur": ["Solapur", "Maharashtra", "India"],
  "kolhapur": ["Kolhapur", "Maharashtra", "India"],
  "amravati": ["Amravati", "Maharashtra", "India"],
  "nanded": ["Nanded", "Maharashtra", "India"],
  "sangli": ["Sangli", "Maharashtra", "India"],
  "satara": ["Satara", "Maharashtra", "India"],
  "latur": ["Latur", "Maharashtra", "India"],
  "akola": ["Akola", "Maharashtra", "India"],
  "jalgaon": ["Jalgaon", "Maharashtra", "India"],
  // Gujarat
  "ahmedabad": ["Ahmedabad", "Gujarat", "India"],
  "surat": ["Surat", "Gujarat", "India"],
  "vadodara": ["Vadodara", "Gujarat", "India"],
  "rajkot": ["Rajkot", "Gujarat", "India"],
  "gandhinagar": ["Gandhinagar", "Gujarat", "India"],
  "bhavnagar": ["Bhavnagar", "Gujarat", "India"],
  "jamnagar": ["Jamnagar", "Gujarat", "India"],
  "anand": ["Anand", "Gujarat", "India"],
  "nadiad": ["Nadiad", "Gujarat", "India"],
  "bharuch": ["Bharuch", "Gujarat", "India"],
  "mehsana": ["Mehsana", "Gujarat", "India"],
  // Madhya Pradesh
  "bhopal": ["Bhopal", "Madhya Pradesh", "India"],
  "indore": ["Indore", "Madhya Pradesh", "India"],
  "gwalior": ["Gwalior", "Madhya Pradesh", "India"],
  "jabalpur": ["Jabalpur", "Madhya Pradesh", "India"],
  "ujjain": ["Ujjain", "Madhya Pradesh", "India"],
  "sagar": ["Sagar", "Madhya Pradesh", "India"],
  "rewa": ["Rewa", "Madhya Pradesh", "India"],
  "satna": ["Satna", "Madhya Pradesh", "India"],
  "dewas": ["Dewas", "Madhya Pradesh", "India"],
  "ratlam": ["Ratlam", "Madhya Pradesh", "India"],
  "chhindwara": ["Chhindwara", "Madhya Pradesh", "India"],
  // Telangana
  "hyderabad": ["Hyderabad", "Telangana", "India"],
  "warangal": ["Warangal", "Telangana", "India"],
  "nizamabad": ["Nizamabad", "Telangana", "India"],
  "karimnagar": ["Karimnagar", "Telangana", "India"],
  "khammam": ["Khammam", "Telangana", "India"],
  "secunderabad": ["Secunderabad", "Telangana", "India"],
  // Andhra Pradesh
  "vijayawada": ["Vijayawada", "Andhra Pradesh", "India"],
  "visakhapatnam": ["Visakhapatnam", "Andhra Pradesh", "India"],
  "vizag": ["Vizag", "Andhra Pradesh", "India"],
  "tirupati": ["Tirupati", "Andhra Pradesh", "India"],
  "guntur": ["Guntur", "Andhra Pradesh", "India"],
  "nellore": ["Nellore", "Andhra Pradesh", "India"],
  "kurnool": ["Kurnool", "Andhra Pradesh", "India"],
  "rajahmundry": ["Rajahmundry", "Andhra Pradesh", "India"],
  // Karnataka
  "bangalore": ["Bangalore", "Karnataka", "India"],
  "bengaluru": ["Bengaluru", "Karnataka", "India"],
  "mysore": ["Mysore", "Karnataka", "India"],
  "mysuru": ["Mysuru", "Karnataka", "India"],
  "mangalore": ["Mangalore", "Karnataka", "India"],
  "mangaluru": ["Mangaluru", "Karnataka", "India"],
  "hubli": ["Hubli", "Karnataka", "India"],
  "dharwad": ["Dharwad", "Karnataka", "India"],
  "belagavi": ["Belagavi", "Karnataka", "India"],
  "belgaum": ["Belgaum", "Karnataka", "India"],
  "davangere": ["Davangere", "Karnataka", "India"],
  "tumkur": ["Tumkur", "Karnataka", "India"],
  "ballari": ["Ballari", "Karnataka", "India"],
  "shivamogga": ["Shivamogga", "Karnataka", "India"],
  // Tamil Nadu
  "chennai": ["Chennai", "Tamil Nadu", "India"],
  "coimbatore": ["Coimbatore", "Tamil Nadu", "India"],
  "madurai": ["Madurai", "Tamil Nadu", "India"],
  "tiruchirappalli": ["Tiruchirappalli", "Tamil Nadu", "India"],
  "trichy": ["Trichy", "Tamil Nadu", "India"],
  "salem": ["Salem", "Tamil Nadu", "India"],
  "tirunelveli": ["Tirunelveli", "Tamil Nadu", "India"],
  "vellore": ["Vellore", "Tamil Nadu", "India"],
  "erode": ["Erode", "Tamil Nadu", "India"],
  "tiruppur": ["Tiruppur", "Tamil Nadu", "India"],
  "dindigul": ["Dindigul", "Tamil Nadu", "India"],
  // Kerala
  "thiruvananthapuram": ["Thiruvananthapuram", "Kerala", "India"],
  "trivandrum": ["Trivandrum", "Kerala", "India"],
  "kochi": ["Kochi", "Kerala", "India"],
  "cochin": ["Cochin", "Kerala", "India"],
  "kozhikode": ["Kozhikode", "Kerala", "India"],
  "calicut": ["Calicut", "Kerala", "India"],
  "thrissur": ["Thrissur", "Kerala", "India"],
  "kollam": ["Kollam", "Kerala", "India"],
  "kannur": ["Kannur", "Kerala", "India"],
  "palakkad": ["Palakkad", "Kerala", "India"],
  "malappuram": ["Malappuram", "Kerala", "India"],
  // West Bengal
  "kolkata": ["Kolkata", "West Bengal", "India"],
  "siliguri": ["Siliguri", "West Bengal", "India"],
  "asansol": ["Asansol", "West Bengal", "India"],
  "durgapur": ["Durgapur", "West Bengal", "India"],
  "howrah": ["Howrah", "West Bengal", "India"],
  "bardhaman": ["Bardhaman", "West Bengal", "India"],
  // Bihar
  "patna": ["Patna", "Bihar", "India"],
  "gaya": ["Gaya", "Bihar", "India"],
  "muzaffarpur": ["Muzaffarpur", "Bihar", "India"],
  "bhagalpur": ["Bhagalpur", "Bihar", "India"],
  "darbhanga": ["Darbhanga", "Bihar", "India"],
  "purnia": ["Purnia", "Bihar", "India"],
  // Jharkhand
  "ranchi": ["Ranchi", "Jharkhand", "India"],
  "jamshedpur": ["Jamshedpur", "Jharkhand", "India"],
  "dhanbad": ["Dhanbad", "Jharkhand", "India"],
  "bokaro": ["Bokaro", "Jharkhand", "India"],
  // Odisha
  "bhubaneswar": ["Bhubaneswar", "Odisha", "India"],
  "cuttack": ["Cuttack", "Odisha", "India"],
  "rourkela": ["Rourkela", "Odisha", "India"],
  "sambalpur": ["Sambalpur", "Odisha", "India"],
  // Punjab
  "ludhiana": ["Ludhiana", "Punjab", "India"],
  "amritsar": ["Amritsar", "Punjab", "India"],
  "jalandhar": ["Jalandhar", "Punjab", "India"],
  "patiala": ["Patiala", "Punjab", "India"],
  "bathinda": ["Bathinda", "Punjab", "India"],
  "pathankot": ["Pathankot", "Punjab", "India"],
  "mohali": ["Mohali", "Punjab", "India"],
  // Chandigarh (UT)
  "chandigarh": ["Chandigarh", "Chandigarh", "India"],
  // Himachal Pradesh
  "shimla": ["Shimla", "Himachal Pradesh", "India"],
  "mandi": ["Mandi", "Himachal Pradesh", "India"],
  "solan": ["Solan", "Himachal Pradesh", "India"],
  "dharamsala": ["Dharamsala", "Himachal Pradesh", "India"],
  "manali": ["Manali", "Himachal Pradesh", "India"],
  // Uttarakhand
  "dehradun": ["Dehradun", "Uttarakhand", "India"],
  "haridwar": ["Haridwar", "Uttarakhand", "India"],
  "roorkee": ["Roorkee", "Uttarakhand", "India"],
  "haldwani": ["Haldwani", "Uttarakhand", "India"],
  "rishikesh": ["Rishikesh", "Uttarakhand", "India"],
  "nainital": ["Nainital", "Uttarakhand", "India"],
  // Chhattisgarh
  "raipur": ["Raipur", "Chhattisgarh", "India"],
  "bhilai": ["Bhilai", "Chhattisgarh", "India"],
  "durg": ["Durg", "Chhattisgarh", "India"],
  "bilaspur": ["Bilaspur", "Chhattisgarh", "India"],
  // Assam
  "guwahati": ["Guwahati", "Assam", "India"],
  "silchar": ["Silchar", "Assam", "India"],
  "dibrugarh": ["Dibrugarh", "Assam", "India"],
  "jorhat": ["Jorhat", "Assam", "India"],
  // Goa
  "panaji": ["Panaji", "Goa", "India"],
  "margao": ["Margao", "Goa", "India"],
  "vasco da gama": ["Vasco da Gama", "Goa", "India"],
  // Jammu & Kashmir
  "srinagar": ["Srinagar", "Jammu & Kashmir", "India"],
  "jammu": ["Jammu", "Jammu & Kashmir", "India"],
  // UAE
  "dubai": ["Dubai", "Dubai", "UAE"],
  "sharjah": ["Sharjah", "Sharjah", "UAE"],
  "abu dhabi": ["Abu Dhabi", "Abu Dhabi", "UAE"],
  "ajman": ["Ajman", "Ajman", "UAE"],
  "ras al khaimah": ["Ras Al Khaimah", "Ras Al Khaimah", "UAE"],
  "umm al quwain": ["Umm Al Quwain", "Umm Al Quwain", "UAE"],
  "fujairah": ["Fujairah", "Fujairah", "UAE"],
  "al ain": ["Al Ain", "Abu Dhabi", "UAE"],
};

/** Returns suggestions (keys) that start with the query string. */
export const getCitySuggestions = (query: string): string[] => {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return Object.keys(CITY_DATA).filter((k) => k.startsWith(q));
};

/** Looks up city data by exact lowercase key. Returns null if not found. */
export const lookupCity = (query: string): { city: string; state: string; country: string } | null => {
  const entry = CITY_DATA[query.toLowerCase().trim()];
  if (!entry) return null;
  return { city: entry[0], state: entry[1], country: entry[2] };
};
